const CLIP_VERSION='noir-atlas-shot/1';
const cloneState=v=>JSON.parse(JSON.stringify(v));
class Director {
 constructor(app){this.app=app;this.recording=false;this.playing=false;this.clip=null;this.playhead=0;this.lastSample=-1;}
 state(){let a=this.app;return {look:normalizeLook(a.look),cameraRig:a.cameraRig.state(),living:a.scene.world?{pairs:cloneState(a.living.pairs),events:cloneState(a.living.events),reserved:[...a.living.reserved],nextSocial:a.living.nextSocial}:null,time:a.time,actors:a.actors.map(p=>{let q={...p};delete q.rigAudit;return cloneState(q);}),selected:a.selected,accents:cloneState(a.accents),settings:{...a.settings},cameraMode:a.cameraMode,cameraOrbit:a.cameraOrbit,focused:a.focused,focusPoint:a.focusPoint?.slice()||null};}
 start(){this.stopPlayback();this.app.setPaused(false);this.clip={schema:CLIP_VERSION,scene:this.app.scene.id,startedAt:this.app.time,duration:0,frames:[]};this.recording=true;this.lastSample=-1;this.nextSample=0;this.capture(true);this.app.toast('开始记录镜头：移动、动作、光影与色彩物件。最长 90 秒。');this.sync();}
 capture(force=false){if(!this.recording)return;const t=this.app.time-this.clip.startedAt;if(force||t+1e-9>=this.nextSample){this.clip.frames.push({t,...this.state()});this.lastSample=t;this.nextSample=Math.max((this.nextSample||0)+1/24,t);this.clip.duration=t;}if(t>=90){this.stop();this.app.toast('90 秒镜头已保存到内存，可导出 JSON。');}this.sync();}
 stop(){if(this.recording){this.captureFinal();this.recording=false;this.playhead=this.clip?.duration||0;}this.sync();}
 captureFinal(){if(!this.clip)return;let t=this.app.time-this.clip.startedAt;if(t>this.lastSample+.0001){this.clip.frames.push({t,...this.state()});this.clip.duration=t;}}
 play(){this.lookOverride=false;this.stop();if(!this.clip||this.clip.frames.length<2){this.app.toast('先录制一段镜头。');return;}if(this.app.scene.id!==this.clip.scene)this.app.loadScene(this.clip.scene,false);this.playhead=0;this.playing=true;this.app.keys.clear();this.app.joy=[0,0];this.app.liftInput=0;this.app.setPaused(false);this.apply(0);this.sync();}
 stopPlayback(){this.playing=false;this.sync();}
 tick(dt){if(!this.playing)return false;this.playhead=Math.min(this.clip.duration,this.playhead+dt);this.apply(this.playhead);if(this.playhead>=this.clip.duration){this.playing=false;this.app.setPaused(true);}this.sync();return true;}
 seek(t){if(!this.clip)return;this.stop();this.playing=false;this.playhead=clamp(t,0,this.clip.duration);if(this.app.scene.id!==this.clip.scene)this.app.loadScene(this.clip.scene,false);this.app.setPaused(true);this.apply(this.playhead);this.sync();}
 apply(t){const frames=this.clip.frames;let lo=0,hi=frames.length-1;while(lo<hi){let m=Math.ceil((lo+hi)/2);if(frames[m].t<=t)lo=m;else hi=m-1;}const a=frames[lo],b=frames[Math.min(lo+1,frames.length-1)],f=b.t>a.t?clamp((t-a.t)/(b.t-a.t),0,1):0;const app=this.app;
 if(a.look&&!this.lookOverride){const look=normalizeLook(a.look);if(JSON.stringify(look)!==JSON.stringify(app.look)){app.look=look;app.syncLookUI?.();}}app.time=lerp(a.time,b.time,f);if(a.cameraRig){const rig=cloneState(a.cameraRig),next=b.cameraRig||rig;rig.yaw+=angleDelta(rig.yaw,next.yaw)*f;rig.pitch=lerp(rig.pitch,next.pitch,f);rig.pan=rig.pan.map((v,i)=>lerp(v,next.pan[i],f));if(rig.storyTarget&&next.storyTarget)rig.storyTarget=rig.storyTarget.map((v,i)=>lerp(v,next.storyTarget[i],f));if(rig.storySpan&&next.storySpan)rig.storySpan=lerp(rig.storySpan,next.storySpan,f);app.cameraRig.restore(rig);}else{app.cameraRig.projection="orthographic";}if(app.scene.world&&a.living){app.living.pairs=cloneState(a.living.pairs);app.living.events=cloneState(a.living.events);app.living.reserved=new Map(a.living.reserved);app.living.nextSocial=a.living.nextSocial;}app.actors=cloneState(a.actors);app.actors.forEach(p=>{const q=b.actors.find(q=>q.id===p.id);if(!q)return;for(const k of ['x','y','z','s','jumpY','flightY','airY','phase','speed','gaitWeight','runWeight','accel','turnRate'])if(typeof p[k]==='number'&&typeof q[k]==='number')p[k]=lerp(p[k],q[k],f);p.angle+=Math.atan2(Math.sin(q.angle-p.angle),Math.cos(q.angle-p.angle))*f;});
 app.selected=Math.min(a.selected,app.actors.length-1);app.accents=cloneState(a.accents);app.accents.forEach((p,i)=>{const q=b.accents[i];if(q)for(const k of ['x','y','z'])p[k]=lerp(p[k],q[k],f);});app.settings=cleanRenderSettings(a.settings);app.cameraMode=a.cameraMode;app.cameraOrbit=lerp(a.cameraOrbit,b.cameraOrbit,f);app.focused=a.focused;app.focusPoint=a.focusPoint? a.focusPoint.map((v,i)=>lerp(v,b.focusPoint?.[i]??v,f)):null;for(const fn of app.scene.dynamic)fn(app.time);app.syncPose();app.syncV2Controls();}
 export(){if(!this.clip?.frames.length){this.app.toast('还没有可导出的镜头。');return;}this.stop();const blob=new Blob([JSON.stringify(this.clip)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='NOIR_ATLAS_shot.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.app.toast('镜头 JSON 已导出。此文件是动画数据，不是视频。');}
 import(data){this.lookOverride=false;const clip=validateClip(data);this.stop();this.stopPlayback();this.clip=clip;this.app.loadScene(clip.scene,false);this.seek(0);this.app.toast('镜头已导入。可拖动时间条或回放。');}
 sync(){const $=id=>document.getElementById(id);if(!$('record-shot'))return;$('record-shot').textContent=this.recording?'■ 停止记录':'● 记录镜头';$('record-shot').classList.toggle('recording',this.recording);$('play-shot').textContent=this.playing?'Ⅱ 停止回放':'▷ 回放';const d=this.clip?.duration||0;$('shot-scrub').max=String(d||1);$('shot-scrub').value=String(this.recording?d:this.playhead);$('shot-scrub').disabled=!d;$('shot-time').textContent=`${(this.recording?d:this.playhead).toFixed(1)} / ${d.toFixed(1)} s`;$('shot-status').textContent=this.recording?'RECORDING / 24 Hz target':this.playing?'PLAYBACK':d?'SHOT READY':'NO SHOT';}
}
function validateClip(input){
 const c=typeof input==='string'?JSON.parse(input):cloneState(input);
 const fail=()=>{throw new Error('镜头格式无效：只接受本引擎导出的有限数值镜头。');};
 const num=x=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<1e7;
 const scan=(v,depth=0)=>{if(depth>15)fail();if(typeof v==='number'&&!num(v))fail();if(v&&typeof v==='object'){if(Array.isArray(v)&&v.length>2300)fail();for(const [k,x]of Object.entries(v)){if(['__proto__','constructor','prototype'].includes(k))fail();scan(x,depth+1);}}};scan(c);
 if(!c||c.schema!==CLIP_VERSION||!Number.isInteger(c.scene)||c.scene<0||c.scene>=SCENE_META.length||!num(c.duration)||c.duration<0||c.duration>91||!num(c.startedAt)||!Array.isArray(c.frames)||c.frames.length<1||c.frames.length>2300)fail();
 let last=-1;for(const f of c.frames){if(!num(f.t)||f.t<0||f.t<last||f.t>c.duration+.001||!num(f.time)||!Array.isArray(f.actors)||f.actors.length<1||f.actors.length>10||!Array.isArray(f.accents)||f.accents.length>12||!['fixed','follow','orbit','profile'].includes(f.cameraMode)||!num(f.cameraOrbit)||typeof f.focused!=='boolean'||!Number.isInteger(f.selected)||f.selected<0||f.selected>=f.actors.length||!f.settings)fail();last=f.t;if(f.cameraRig){const r=f.cameraRig;if(!['perspective','orthographic'].includes(r.projection)||!num(r.yaw)||!num(r.pitch)||!Array.isArray(r.pan)||r.pan.length!==3||r.pan.some(v=>!num(v)))fail();if(r.storyTarget!==null&&(!Array.isArray(r.storyTarget)||r.storyTarget.length!==3||r.storyTarget.some(v=>!num(v))))fail();if(r.storySpan!==null&&(!num(r.storySpan)||r.storySpan<3||r.storySpan>80))fail();}if(f.focusPoint!==null&&(!Array.isArray(f.focusPoint)||f.focusPoint.length!==3||f.focusPoint.some(n=>!num(n))))fail();
 const ids=new Set();for(const a of f.actors){if(!Number.isInteger(a.id)||ids.has(a.id)||!Object.hasOwn(labels,a.pose)||typeof a.flying!=='boolean')fail();ids.add(a.id);for(const k of ['x','y','z','angle','phase','jumpY','s','poseSince','flightY','airY','velocity','blendAt'])if(!num(a[k]))fail();if(a.target&&(!num(a.target.x)||!num(a.target.z)||(a.target.s!==undefined&&!num(a.target.s))))fail();for(const k of ['moving','auto','landing'])if(typeof a[k]!=='boolean')fail();for(const k of ['turnFrom','autoHeading'])if(a[k]!==undefined&&!num(a[k]))fail();if(a.blendFrom){for(const k of ['pelvis','lean','roll','headYaw','headPitch','rootTilt','rootRoll'])if(!num(a.blendFrom[k]))fail();for(const k of ['feet','hands','poles'])if(!Array.isArray(a.blendFrom[k])||a.blendFrom[k].length!==2||a.blendFrom[k].some(v=>!Array.isArray(v)||v.length!==3||v.some(n=>!num(n))))fail();if(!Array.isArray(a.blendFrom.pitches)||a.blendFrom.pitches.length!==2||a.blendFrom.pitches.some(n=>!num(n)))fail();}}
 for(const p of f.accents){if(!['sphere','box','ring','diamond'].includes(p.type)||!num(p.size)||p.size<=0||p.size>2||!Array.isArray(p.tint)||p.tint.length!==3||p.tint.some(x=>!num(x)||x<0||x>1))fail();for(const k of ['x','y','z','phase'])if(!num(p[k]))fail();}
 for(const k of ['lightShift','contrast','haze','grain','zoom','exposure'])if(!num(f.settings[k]))fail();if(f.settings.zoom<.1||f.settings.zoom>12||typeof f.settings.accents!=='boolean')fail();}
 if(c.frames[0].t!==0||Math.abs(c.frames.at(-1).t-c.duration)>.01)fail();return c;
}

// Scene-specific scores: deliberate travel, rests, attention and gestures.
// Deterministic, local and offline. No language-model agent/API is involved.
