const Geo = {
 disc(n=96){const p=[0,0,0],normal=[0,0,1],normals=[...normal],ix=[];for(let i=0;i<=n;i++){const a=i/n*Math.PI*2;p.push(Math.cos(a),Math.sin(a),0);normals.push(...normal);if(i>0)ix.push(0,i,i+1);}return {p,n:normals,ix};},
 torus(major=1,tube=.14,nx=32,ny=10){let p=[],n=[],ix=[];for(let i=0;i<=nx;i++){let u=i/nx*Math.PI*2;for(let j=0;j<=ny;j++){let v=j/ny*Math.PI*2,cv=Math.cos(v),sv=Math.sin(v),cu=Math.cos(u),su=Math.sin(u);p.push((major+tube*cv)*cu,(major+tube*cv)*su,tube*sv);n.push(cv*cu,cv*su,sv);}}for(let i=0;i<nx;i++)for(let j=0;j<ny;j++){let a=i*(ny+1)+j,b=a+ny+1;ix.push(a,b,a+1,a+1,b,b+1);}return {p,n,ix};},
 ribbon(points,width,depth){let p=[],n=[],ix=[],left=[],right=[];let normals=points.slice(0,-1).map((a,i)=>{let b=points[i+1],len=Math.hypot(b[0]-a[0],b[1]-a[1]);return [-(b[1]-a[1])/len,(b[0]-a[0])/len];});for(let i=0;i<points.length;i++){let a=normals[Math.max(0,i-1)],b=normals[Math.min(normals.length-1,i)],m=V.norm([a[0]+b[0],0,a[1]+b[1]]),d=width*.5/Math.max(.15,m[0]*b[0]+m[2]*b[1]);left.push([points[i][0]+m[0]*d,0,points[i][1]+m[2]*d]);right.push([points[i][0]-m[0]*d,0,points[i][1]-m[2]*d]);}const quad=(vs,normal)=>{let k=p.length/3;vs.forEach(v=>{p.push(...v);n.push(...normal);});ix.push(k,k+1,k+2,k,k+2,k+3);};for(let i=0;i<points.length-1;i++){quad([left[i],right[i],right[i+1],left[i+1]],[0,1,0]);let nn=normals[i];quad([left[i],left[i+1],[left[i+1][0],-depth,left[i+1][2]],[left[i][0],-depth,left[i][2]]],[nn[0],0,nn[1]]);quad([right[i+1],right[i],[right[i][0],-depth,right[i][2]],[right[i+1][0],-depth,right[i+1][2]]],[-nn[0],0,-nn[1]]);}for(let i of [0,points.length-1]){let nn=normals[i===0?0:normals.length-1],sign=i===0?-1:1;quad([left[i],right[i],[right[i][0],-depth,right[i][2]],[left[i][0],-depth,left[i][2]]],[nn[1]*sign,0,-nn[0]*sign]);}return {p,n,ix};},
 box(){const p=[],n=[],ix=[];const faces=[[[1,0,0],[[1,-1,-1],[1,1,-1],[1,1,1],[1,-1,1]]],[[-1,0,0],[[-1,-1,1],[-1,1,1],[-1,1,-1],[-1,-1,-1]]],[[0,1,0],[[-1,1,-1],[-1,1,1],[1,1,1],[1,1,-1]]],[[0,-1,0],[[-1,-1,1],[-1,-1,-1],[1,-1,-1],[1,-1,1]]],[[0,0,1],[[1,-1,1],[1,1,1],[-1,1,1],[-1,-1,1]]],[[0,0,-1],[[-1,-1,-1],[-1,1,-1],[1,1,-1],[1,-1,-1]]]];for(const [normal,vs] of faces){let k=p.length/3;for(const v of vs){p.push(...v.map(a=>a*.5));n.push(...normal);}ix.push(k,k+1,k+2,k,k+2,k+3);}return {p,n,ix};},
 sphere(nx=20,ny=12,rough=0){let p=[],n=[],ix=[];for(let j=0;j<=ny;j++){let t=j/ny*Math.PI;for(let i=0;i<=nx;i++){let a=i/nx*Math.PI*2,x=Math.sin(t)*Math.cos(a),y=Math.cos(t),z=Math.sin(t)*Math.sin(a);let r=1+rough*(Math.sin(x*4+y*3)*Math.cos(z*3-1)+.45*Math.sin(z*6+y*4));p.push(x*r,y*r,z*r);n.push(x,y,z);}}for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){let a=j*(nx+1)+i,b=a+nx+1;ix.push(a,b,a+1,a+1,b,b+1);}return {p,n,ix};},
 // Continuous elliptical rings form anatomy (not sticks or ball-jointed toys).
 loft(rings,sides=12){let p=[],n=[],ix=[];for(let j=0;j<rings.length;j++){let [y,rx,rz,oz=0]=rings[j],pr=rings[Math.max(0,j-1)],ne=rings[Math.min(rings.length-1,j+1)];for(let i=0;i<=sides;i++){let a=i/sides*2*Math.PI,c=Math.cos(a),s=Math.sin(a),slope=((ne[1]-pr[1])*c*c+(ne[2]-pr[2])*s*s)/Math.max(.001,ne[0]-pr[0]),normal=V.norm([c/rx,-slope/Math.max(rx,rz),s/rz]);p.push(c*rx,y,s*rz+oz);n.push(...normal);}}for(let j=0;j<rings.length-1;j++)for(let i=0;i<sides;i++){let a=j*(sides+1)+i,b=a+sides+1;ix.push(a,a+1,b,a+1,b+1,b);}return {p,n,ix};}
};
function linkMatrix(a,b,rx,rz=rx){let d=V.sub(b,a),len=Math.hypot(...d),y=V.norm(d),x=V.norm(V.cross(Math.abs(y[2])<.9?[0,0,1]:[1,0,0],y)),z=V.cross(x,y);return new Float32Array([x[0]*rx,x[1]*rx,x[2]*rx,0,y[0]*len,y[1]*len,y[2]*len,0,z[0]*rz,z[1]*rz,z[2]*rz,0,a[0],a[1],a[2],1]);}

