class NavGrid {
 constructor(bounds,valid,cell=.42){this.bounds=bounds;this.valid=valid;this.cell=cell;this.nx=Math.ceil((bounds[1]-bounds[0])/cell);this.nz=Math.ceil((bounds[3]-bounds[2])/cell);this.free=new Uint8Array(this.nx*this.nz);this.regions=new Int32Array(this.free.length).fill(-1);for(let j=0;j<this.nz;j++)for(let i=0;i<this.nx;i++){const p=this.world(i,j);this.free[j*this.nx+i]=valid(...p)?1:0;}this.components();}
 world(i,j){return [this.bounds[0]+(i+.5)*this.cell,this.bounds[2]+(j+.5)*this.cell];}
 index(x,z){const i=Math.floor((x-this.bounds[0])/this.cell),j=Math.floor((z-this.bounds[2])/this.cell);return i>=0&&j>=0&&i<this.nx&&j<this.nz?j*this.nx+i:-1;}
 point(k){return this.world(k%this.nx,Math.floor(k/this.nx));}
 components(){let id=0;for(let k=0;k<this.free.length;k++){if(!this.free[k]||this.regions[k]>=0)continue;const q=[k];this.regions[k]=id;for(let n=0;n<q.length;n++){const a=q[n],i=a%this.nx,j=Math.floor(a/this.nx);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=i+dx,z=j+dz,b=z*this.nx+x;if(x>=0&&z>=0&&x<this.nx&&z<this.nz&&this.free[b]&&this.regions[b]<0){this.regions[b]=id;q.push(b);}}}id++;}this.componentCount=id;}
 nearest(x,z,region=null){let best=-1,d=Infinity;const k=this.index(x,z);if(k>=0&&this.free[k]&&(region===null||this.regions[k]===region)&&this.valid(x,z))return [x,z,k];for(let a=0;a<this.free.length;a++){if(!this.free[a]||(region!==null&&this.regions[a]!==region))continue;const p=this.point(a),dist=(p[0]-x)**2+(p[1]-z)**2;if(dist<d){d=dist;best=a;}}return best<0?null:[...this.point(best),best];}
 clear(a,b){const n=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/(this.cell*.22)));for(let i=0;i<=n;i++){const t=i/n;if(!this.valid(lerp(a[0],b[0],t),lerp(a[1],b[1],t)))return false;}return true;}
 move(x,z,tx,tz){let p=[x,z],dx=tx-x,dz=tz-z,n=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.095));for(let i=1;i<=n;i++){const q=[x+dx*i/n,z+dz*i/n];if(this.valid(...q))p=q;else {const a=[q[0],p[1]],b=[p[0],q[1]];if(this.valid(...a))p=a;else if(this.valid(...b))p=b;}}return p;}
 route(x,z,tx,tz){const s=this.nearest(x,z),e=this.nearest(tx,tz);if(!s||!e||this.regions[s[2]]!==this.regions[e[2]])return null;const start=[s[0],s[1]],end=[e[0],e[1]];if(this.clear(start,end))return [end];const n=this.free.length,dist=new Float32Array(n).fill(Infinity),prev=new Int32Array(n).fill(-1),closed=new Uint8Array(n),heap=[];dist[s[2]]=0;
 const push=(k,v)=>{let i=heap.length;heap.push([k,v]);while(i>0){const p=(i-1)>>1;if(heap[p][1]<=v)break;heap[i]=heap[p];i=p;}heap[i]=[k,v];};
 const pop=()=>{const a=heap[0],end=heap.pop();if(heap.length){let i=0;while(i*2+1<heap.length){let c=i*2+1;if(c+1<heap.length&&heap[c+1][1]<heap[c][1])c++;if(end[1]<=heap[c][1])break;heap[i]=heap[c];i=c;}heap[i]=end;}return a;};
 const ex=e[2]%this.nx,ez=Math.floor(e[2]/this.nx);push(s[2],0);while(heap.length){const [k]=pop();if(closed[k])continue;closed[k]=1;if(k===e[2])break;const i=k%this.nx,j=Math.floor(k/this.nx);for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dz)continue;const xx=i+dx,zz=j+dz,b=zz*this.nx+xx;if(xx<0||zz<0||xx>=this.nx||zz>=this.nz||!this.free[b]||closed[b])continue;if(dx&&dz&&(!this.free[j*this.nx+xx]||!this.free[zz*this.nx+i]))continue;const d=dist[k]+Math.hypot(dx,dz);if(d<dist[b]){dist[b]=d;prev[b]=k;push(b,d+Math.hypot(ex-xx,ez-zz));}}}
 if(!closed[e[2]])return null;let k=e[2],p=[end];while(k!==s[2]){p.push(this.point(k));k=prev[k];if(k<0)return null;}p.push(start);p.reverse();let smooth=[],anchor=0;while(anchor<p.length-1){let next=anchor+1;for(let j=p.length-1;j>anchor+1;j--)if(this.clear(p[anchor],p[j])){next=j;break;}smooth.push(p[next]);anchor=next;}return smooth;}
}
function installNavigation(sc){const r=.24,b=sc.bounds;const valid=(x,z)=>{if(x<b[0]+r||x>b[1]-r||z<b[2]+r||z>b[3]-r)return false;if(sc.walkMask&&!sc.walkMask(x,z,r))return false;for(const o of sc.blockers){if(o.kind==='circle'){if(Math.hypot(x-o.x,z-o.z)<o.r+r)return false;}else if(x>o.x-o.w/2-r&&x<o.x+o.w/2+r&&z>o.z-o.d/2-r&&z<o.z+o.d/2+r)return false;}return true;};sc.nav=new NavGrid(b,valid,.42);sc.constrain=(x,z)=>{const p=sc.nav.nearest(x,z);return p?p.slice(0,2):[sc.spawns[0][0],sc.spawns[0][1]];};for(const s of sc.spots){if(!s.seat)continue;const candidates=[];for(const r of [.85,1.05])for(const delta of [Math.PI/2,-Math.PI/2,Math.PI,0])candidates.push([s.x+Math.sin(s.angle+delta)*r,s.z+Math.cos(s.angle+delta)*r]);s.approach=candidates.find(q=>valid(...q)&&sc.nav.clear(q,[s.x,s.z]))||[s.x,s.z];}return sc;}

/* Original procedural architecture: no background screenshots or remote assets. */
