App.prototype.updateCamera=function(){this.cameraRig.update();};
App.prototype.screen=function(p){const q=M.transform(this.camera.vp,p),w=q[3],x=q[0]/w,y=q[1]/w,z=q[2]/w;return {x:(x*.5+.5)*innerWidth,y:(.5-y*.5)*innerHeight,z,w,visible:w>0&&z>=-1&&z<=1&&Math.abs(x)<1.12&&Math.abs(y)<1.12};};
App.prototype.actorAt=function(x,y){let nearest=-1,best=matchMedia('(pointer:coarse)').matches?27:19;this.actors.forEach((a,i)=>{const head=this.screen(a.headWorld||[a.x,baseY(a)+1.85,a.z]),feet=this.screen([a.x,baseY(a),a.z]);if(!head.visible||!feet.visible)return;const h=Math.hypot(head.x-feet.x,head.y-feet.y),dx=head.x-feet.x,dy=head.y-feet.y,t=clamp(((x-feet.x)*dx+(y-feet.y)*dy)/Math.max(h*h,.01),0,1),distance=Math.hypot(x-feet.x-dx*t,y-feet.y-dy*t)-Math.min(22,h*.12);if(distance<best){best=distance;nearest=i;}});return nearest;};
App.prototype.planeAt=function(x,y,height){const {a,d}=this.ray(x,y);if(Math.abs(d[1])<1e-7)return null;const t=(height-a[1])/d[1];return t>=0&&t<=1?[a[0]+d[0]*t,a[2]+d[2]*t]:null;};
App.prototype.drawWorldHUD=function(){this.dialogue.draw();};
App.prototype.syncCameraUI=function(){if(!$('view-scale'))return;$('view-scale').textContent=Math.round(this.settings.zoom*100)+'%';$('view-projection').textContent=this.cameraRig.projection==='perspective'?'透视 3D':'正交 3D';$('view-lock').setAttribute('aria-pressed',String(this.cameraRig.lock));$('zoom').value=this.settings.zoom;$('zoom-value').value=this.settings.zoom.toFixed(2);};
App.prototype.syncDialogueUI=function(){if(!$('dialogue-enabled'))return;$('dialogue-enabled').checked=this.dialogue.enabled;$('voice-enabled').checked=this.dialogue.voice;$('ambient-enabled').checked=this.dialogue.ambient;$('cast-names').checked=this.dialogue.names;};
App.prototype.renderCast=function(){if(!$('cast-list'))return;const list=$('cast-list');list.replaceChildren();this.actors.forEach((a,i)=>{const el=document.createElement('button');el.className='cast-item'+(i===this.selected?' selected':'');el.dataset.actor=String(a.id);const dot=document.createElement('span');dot.style.background=castColour(a).hex;el.append(dot,document.createTextNode(appearanceOf(a).name));el.onclick=()=>{this.selected=i;this.syncPose();this.renderCast();};list.append(el);});
 const ap=appearanceOf(this.actor);$('cast-name').value=ap.name;$('cast-hat').value=ap.hat;$('cast-outfit').value=ap.outfit;$('cast-colours').replaceChildren();CAST_COLOURS.forEach((c,i)=>{const el=document.createElement('button');el.className='swatch'+(i===ap.colour?' selected':'');el.setAttribute('aria-label',c.name);el.setAttribute('aria-pressed',String(i===ap.colour));const dot=document.createElement('span');dot.style.background=c.hex;el.append(dot);el.onclick=()=>{this.actor.appearance={...appearanceOf(this.actor),colour:i};this.renderCast();};$('cast-colours').append(el);});
};
App.prototype.setupV5=function(){const app=this;this.cameraRig.bind();
 const closePanels=()=>{for(const id of ['cast-panel','theatre-panel','settings','motion-panel','director-panel','places-panel','social-panel'])$(id).hidden=true;};
 $('theatre-toggle').onclick=()=>{const open=$('theatre-panel').hidden;closePanels();$('theatre-panel').hidden=!open;this.syncDialogueUI();};
 $('cast-toggle').onclick=()=>{const open=$('cast-panel').hidden;closePanels();$('cast-panel').hidden=!open;this.renderCast();};
 $('theatre-close').onclick=()=>$('theatre-panel').hidden=true;$('cast-close').onclick=()=>$('cast-panel').hidden=true;
 $('view-in').onclick=()=>this.cameraRig.zoomBy(1.25);$('view-out').onclick=()=>this.cameraRig.zoomBy(.8);$('view-home').onclick=()=>{this.theatre.tracking=null;this.cameraRig.frameAll();};
 $('view-projection').onclick=()=>{this.cameraRig.projection=this.cameraRig.projection==='perspective'?'orthographic':'perspective';this.syncCameraUI();};$('view-lock').onclick=()=>{this.cameraRig.lock=!this.cameraRig.lock;this.syncCameraUI();};
 $('focus').onclick=()=>this.focused?this.cameraRig.frameAll():this.cameraRig.frameActor();$('cast-focus').onclick=()=>{this.theatre.tracking=null;this.cameraRig.frameActor();$('cast-panel').hidden=true;};
 $('follow-world').onclick=()=>{this.theatre.tracking=null;this.cameraRig.frameActor();};
 $('cast-control').onclick=()=>{this.exhibition.takeover(this.actor);this.cameraRig.frameActor();$('cast-panel').hidden=true;this.syncPose();};
 $('cast-name').oninput=e=>{this.actor.appearance={...appearanceOf(this.actor),name:e.target.value.trim().slice(0,12)||'无名'};const b=$('cast-list').querySelector('.selected');if(b)b.lastChild.textContent=this.actor.appearance.name;};
 $('cast-hat').onchange=e=>{this.actor.appearance={...appearanceOf(this.actor),hat:e.target.value};};$('cast-outfit').onchange=e=>{this.actor.appearance={...appearanceOf(this.actor),outfit:e.target.value};};
 $('cast-say').onclick=()=>{this.exhibition.takeover(this.actor);this.setPaused(false);this.living.pose(this.actor,this.actor.seatId?'tea':'talk');this.dialogue.enabled=true;this.dialogue.say(this.actor,$('cast-line').value||'今天的光，和昨天不一样。',10);this.cameraRig.frameActor();$('cast-panel').hidden=true;};
 $('cast-names').onchange=e=>this.dialogue.names=e.target.checked;
 for(const [id,key]of [['dialogue-enabled','enabled'],['ambient-enabled','ambient']])$(id).onchange=e=>{this.dialogue[key]=e.target.checked;};$('voice-enabled').onchange=e=>this.dialogue.toggleVoice(e.target.checked);
 $('dialogue-font').oninput=e=>{this.dialogue.fontSize=Number(e.target.value);$('dialogue-font-value').value=e.target.value+' px';};
 $('story-list').replaceChildren();DRAMA_SCRIPTS.forEach((s,i)=>{const b=document.createElement('button');b.className='story-item';b.dataset.story=String(i);const glyph=document.createElement('span');glyph.className='play-glyph';glyph.textContent='▷';const words=document.createElement('span'),title=document.createElement('strong'),note=document.createElement('small');title.textContent=s.title;note.textContent=s.description;words.append(title,note);b.append(glyph,words);b.onclick=()=>{$('script-editor').value=JSON.stringify(s,null,2);try{this.theatre.start(s);}catch(e){this.toast(e.message,5000);}};$('story-list').append(b);});
 $('theatre-pause').onclick=()=>{this.setPaused(!this.paused);this.theatre.sync();};$('theatre-next').onclick=()=>{if(this.theatre.active){const b=this.theatre.script.beats[this.theatre.index];if(b?.type==='move'){for(const t of b.targets)this.living.cancel(this.theatre.actor(t.role));}this.theatre.advance();this.setPaused(false);}};$('theatre-stop').onclick=()=>this.theatre.stop(true);
 $('script-editor').value=JSON.stringify(DRAMA_SCRIPTS[0],null,2);
 $('script-run').onclick=()=>{try{const s=validateDrama($('script-editor').value);$('script-error').textContent='';this.theatre.start(s);}catch(e){$('script-error').textContent=e.message;}};
 const downloadJSON=(value,name)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),el=document.createElement('a');el.download=name;el.href=url;el.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('script-save').onclick=()=>{try{downloadJSON(validateDrama($('script-editor').value),'NOIR_drama.json');$('script-error').textContent='';}catch(e){$('script-error').textContent=e.message;}};
 $('script-import').onclick=()=>$('script-file').click();$('script-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>300000)throw new Error('短剧文件不能超过 300 KB');const text=await file.text(),s=validateDrama(text);$('script-editor').value=JSON.stringify(s,null,2);$('script-error').textContent='已导入。点击“验证并播放”开始。';}catch(err){$('script-error').textContent=err.message;}e.target.value='';};
 document.addEventListener('keydown',e=>{if(e.code==='Escape'){closePanels();}},{capture:true});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)this.dialogue.cancelVoice();});window.addEventListener('pagehide',()=>this.dialogue.cancelVoice());
 $('screenshot').onclick=()=>this.export();
 const oldToggle=$('exhibition-toggle').onclick;$('exhibition-toggle').onclick=()=>{if(this.theatre.active)this.theatre.stop(true);oldToggle();};
 this.syncCameraUI();this.syncDialogueUI();this.renderCast();
};
const _v4Paused=App.prototype.setPaused;
App.prototype.setPaused=function(v){_v4Paused.call(this,v);if(v)this.dialogue?.cancelVoice();this.theatre?.sync();};
const _v4Sync=App.prototype.syncPose;
App.prototype.syncPose=function(){_v4Sync.call(this);if(this.actor)$('actor-id').textContent=appearanceOf(this.actor).name;this.syncCameraUI?.();};
const _v4Add=App.prototype.addPerson;
App.prototype.addPerson=function(){_v4Add.call(this);this.renderCast?.();};
const _v4Takeover=Exhibition.prototype.takeover;
Exhibition.prototype.takeover=function(a=this.app.actor){if(this.app.theatre?.active)this.app.theatre.stop(false);_v4Takeover.call(this,a);};
const _v4Load=App.prototype.loadScene;
App.prototype.loadScene=function(id,transition=true){if(!transition){this.wardrobe??=new Map();for(const a of this.actors)this.wardrobe.set(a.id,appearanceOf(a));this.theatre?.stop(false);this.dialogue?.clear();}_v4Load.call(this,id,transition);if(!transition){for(const a of this.actors)if(this.wardrobe.has(a.id))a.appearance={...this.wardrobe.get(a.id)};this.dialogue.nextAmbient=this.time+7;this.renderCast?.();this.syncPose();this.syncCameraUI?.();}};
const _v4DirectorPlay=Director.prototype.play;
Director.prototype.play=function(){this.app.theatre.stop(false);this.app.dialogue.cancelVoice();_v4DirectorPlay.call(this);};
// Screenshot composition includes the current readable head-anchored captions.
App.prototype.export=function(){try{this.draw();const c=document.createElement('canvas');c.width=this.canvas.width;c.height=this.canvas.height;const g=c.getContext('2d');g.drawImage(this.canvas,0,0);g.scale(c.width/innerWidth,c.height/innerHeight);
 for(const b of this.dialogue.layouts){g.strokeStyle=b.colour;g.lineWidth=1;g.beginPath();g.moveTo(clamp(b.anchor.x,b.x+15,b.x+b.w-15),b.y+b.h);g.lineTo(b.anchor.x,b.anchor.y);g.stroke();g.fillStyle='#f8f6f0';g.beginPath();g.roundRect(b.x,b.y,b.w,b.h,8);g.fill();g.fillStyle=b.colour;g.fillRect(b.x,b.y+8,2,b.h-16);g.font='10px sans-serif';g.fillStyle='#555';g.fillText(b.name,b.x+12,b.y+18);g.font=`${b.font}px sans-serif`;g.fillStyle='#252622';let line='',y=b.y+38;for(const ch of Array.from(b.text)){if(g.measureText(line+ch).width>b.w-24){g.fillText(line,b.x+12,y);line='';y+=b.font*1.65;}line+=ch;}g.fillText(line,b.x+12,y);}
 const a=document.createElement('a');a.download='NOIR_ATLAS_3D_frame.png';a.href=c.toDataURL('image/png');a.click();this.toast('已保存三维画面与头顶对白，不含操作面板。');}catch(e){this.toast('导出失败：'+e.message);}};
